
apiVersion: v1
kind: ConfigMap
metadata:
  name: jx-auth-config
  labels:
    jenkins.io/created-by: jx
    jenkins.io/config-type: auth
data:
  gitAuth.yaml: |
    currentserver: "https://github.com"
    defaultusername: "jenkins-x-bot"
    pipelineserver: "https://github.com"
    pipelineusername: "jenkins-x-bot"
    servers:
    - currentuser: "jenkins-x-bot"
      kind: "github"
      name: "github"
      url: "https://github.com"
      users:
      - apitoken: "vault:oss-weasel/pipelineUser:token"
        bearertoken: ""
        username: "jenkins-x-bot"
